# Generated by Django 3.2.8 on 2021-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internalurl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
